export const dynamic = "force-static";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="mb-2 text-sm font-semibold text-ink">{title}</h2>
      <div className="space-y-2 text-sm text-ink/70 leading-relaxed">{children}</div>
    </section>
  );
}

function H3({ children }: { children: React.ReactNode }) {
  return <h3 className="mt-4 mb-1 text-xs font-semibold uppercase tracking-wide text-muted/60">{children}</h3>;
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-surface">
      <div className="mx-auto max-w-md px-6 pb-20 pt-14">
        <a
          href="/"
          className="mb-8 inline-flex items-center gap-1.5 text-xs text-muted/60 hover:text-ink/60 transition-colors"
        >
          <svg viewBox="0 0 16 16" className="h-3.5 w-3.5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M10 12L6 8l4-4" />
          </svg>
          Back
        </a>

        <h1 className="text-2xl font-semibold text-ink">Privacy Policy and Terms of Use</h1>
        <p className="mt-1 text-xs text-muted/60">Effective date: April 5, 2025. Governing law: Province of Ontario, Canada.</p>
        <p className="mt-3 text-xs text-ink/60 leading-relaxed">
          By creating an account or using WhatYouAte (the "App"), you agree to these terms in full. If you do not agree, do not use the App.
        </p>

        {/* ── TERMS OF USE ───────────────────────────────────── */}
        <p className="mt-8 text-[10px] font-bold uppercase tracking-widest text-muted/40">Terms of Use</p>
        <div className="mt-4 space-y-6">

          <Section title="1. Not Medical Advice">
            <p>
              WhatYouAte is a general wellness and food-logging tool. Nothing in the App, including nutrition estimates, nudges, insights, or any other output, constitutes medical advice, dietetic advice, clinical nutrition guidance, or a substitute for the advice of a qualified healthcare professional.
            </p>
            <p>
              All calorie and macronutrient estimates are generated by artificial intelligence and are approximations only. They may be inaccurate, incomplete, or not applicable to your specific circumstances. You should not rely on the App to diagnose, treat, manage, or prevent any health condition.
            </p>
            <p>
              If you have or suspect a health condition, dietary disorder, or medical concern, consult a qualified healthcare provider before making changes to your diet or lifestyle.
            </p>
          </Section>

          <Section title="2. Assumption of Risk">
            <p>
              You acknowledge and accept that: (a) AI-generated nutrition data is an estimate and may be materially incorrect; (b) the App does not account for allergies, intolerances, medications, or medical conditions unless explicitly entered by you, and even then provides no clinical guarantee; (c) any decisions you make regarding your diet, exercise, or health based on App outputs are made at your sole risk and discretion.
            </p>
            <p>
              By using the App you voluntarily assume all risks associated with reliance on the App and its outputs.
            </p>
          </Section>

          <Section title="3. Limitation of Liability">
            <p>
              To the fullest extent permitted by applicable law, WhatYouAte, its founders, operators, employees, contractors, and affiliated parties (collectively, "WhatYouAte") shall have no liability whatsoever arising from or in connection with your use of, or inability to use, the App, including any reliance on nutrition data, nudges, or insights generated by the App.
            </p>
            <p>
              Without limiting the foregoing, the total aggregate liability of WhatYouAte for any and all claims, losses, damages, costs, or expenses of any kind, whether arising in contract, tort (including negligence), strict liability, or otherwise, shall not exceed the greater of: (a) the amount you paid to WhatYouAte in the thirty (30) days immediately preceding the event giving rise to the claim; or (b) ten Canadian dollars (CAD $10.00).
            </p>
            <p>
              In no event shall WhatYouAte be liable for any indirect, incidental, consequential, special, punitive, or exemplary damages, including loss of data, personal injury, health-related harm, or economic loss, even if advised of the possibility of such damages.
            </p>
            <p>
              Some jurisdictions do not permit the exclusion or limitation of certain warranties or liabilities. In such jurisdictions, liability is limited to the minimum extent required by applicable law.
            </p>
          </Section>

          <Section title="4. No Warranties">
            <p>
              The App is provided on an "as is" and "as available" basis without warranties of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, accuracy, or non-infringement. WhatYouAte does not warrant that the App will be error-free, uninterrupted, or free of harmful components.
            </p>
          </Section>

          <Section title="5. Eligibility">
            <p>
              You must be at least 13 years of age to use the App. By using the App you represent that you meet this requirement. Users between 13 and 18 should have parental or guardian consent before use. WhatYouAte does not knowingly collect personal information from children under 13.
            </p>
          </Section>

          <Section title="6. Acceptable Use">
            <p>
              You agree not to: (a) use the App for any unlawful purpose; (b) attempt to reverse-engineer, scrape, or interfere with the App or its infrastructure; (c) share your account credentials with others; or (d) use the App in any manner that could harm WhatYouAte or other users.
            </p>
          </Section>

          <Section title="7. Subscriptions and Billing">
            <p>
              Paid subscriptions are billed in advance on a recurring basis. You may cancel at any time through your account settings or app store. Cancellation takes effect at the end of the current billing period. Refunds are not provided for partial billing periods except where required by applicable law.
            </p>
          </Section>

          <Section title="8. Termination">
            <p>
              WhatYouAte may suspend or terminate your access at any time for violation of these terms or for any other reason, with or without notice. You may terminate your account at any time using the "Delete account" option in your Profile.
            </p>
          </Section>

          <Section title="9. Governing Law and Jurisdiction">
            <p>
              These terms and any dispute arising from your use of the App shall be governed exclusively by the laws of Canada and the laws of the Province of Ontario applicable therein, without regard to conflicts of law principles. You irrevocably submit to the exclusive jurisdiction of the courts of the Province of Ontario for the resolution of any such dispute.
            </p>
            <p>
              If you access the App from outside Canada, you do so at your own initiative and are responsible for compliance with any applicable local laws. Nothing herein limits WhatYouAte's right to seek injunctive or equitable relief in any competent court.
            </p>
          </Section>

          <Section title="10. Changes to Terms">
            <p>
              WhatYouAte reserves the right to modify these terms at any time. Material changes will be communicated in the App. Continued use of the App after changes are posted constitutes acceptance of the revised terms.
            </p>
          </Section>

        </div>

        {/* ── PRIVACY POLICY ─────────────────────────────────── */}
        <p className="mt-12 text-[10px] font-bold uppercase tracking-widest text-muted/40">Privacy Policy</p>
        <div className="mt-4 space-y-6">

          <Section title="11. Information We Collect">
            <H3>Account information</H3>
            <p>When you create an account we collect your email address and, optionally, your first and last name.</p>
            <H3>Profile information</H3>
            <p>To generate personalized nutrition targets we collect optional profile data including age, sex, height, weight, goal direction, activity level, and dietary restrictions. You may skip or update any of these at any time.</p>
            <H3>Usage data</H3>
            <p>We collect food logs, meal photos (see below), workout logs, supplement entries, and in-app activity to power your insights and nudges.</p>
            <H3>Device and technical data</H3>
            <p>We may collect basic technical information such as device type, operating system version, and crash logs solely for the purpose of maintaining app stability.</p>
          </Section>

          <Section title="12. Meal Photos">
            <p>
              Photos you capture are transmitted over an encrypted connection to our AI analysis provider (Anthropic) for the purpose of identifying food items and estimating nutritional content. Photos are not permanently stored on WhatYouAte's servers. They are processed and discarded after analysis is complete. A compressed thumbnail may be stored locally on your device for display in your food log.
            </p>
          </Section>

          <Section title="13. How We Use Your Information">
            <p>We use your information to: (a) operate and improve the App; (b) generate personalized nutrition estimates, nudges, and insights; (c) calculate progress toward your stated health goals; (d) communicate service-related information to you; and (e) comply with legal obligations.</p>
            <p>We do not sell your personal information to third parties. We do not use your personal information for advertising purposes.</p>
          </Section>

          <Section title="14. Third-Party Service Providers">
            <p>We share data with the following processors only to the extent necessary to operate the App:</p>
            <ul className="mt-1.5 space-y-1.5 list-disc list-inside">
              <li><span className="font-medium text-ink/80">Supabase</span>: secure database hosting and user authentication.</li>
              <li><span className="font-medium text-ink/80">Anthropic</span>: AI-powered meal analysis and nudge generation.</li>
            </ul>
            <p className="mt-2">Each provider operates under its own privacy policy and data processing agreements. WhatYouAte is not responsible for the data practices of these third parties beyond the contractual safeguards in place.</p>
          </Section>

          <Section title="15. Data Retention and Deletion">
            <p>
              We retain your data for as long as your account is active. You may delete your account and all associated data at any time using the "Delete account" option in your Profile. Upon deletion, your personal data is removed from our systems within a reasonable period, except where retention is required by law.
            </p>
          </Section>

          <Section title="16. Security">
            <p>
              We use industry-standard security measures including encryption in transit (TLS) and encryption at rest to protect your data. No method of transmission over the internet is 100% secure. While we take reasonable steps to protect your information, we cannot guarantee absolute security.
            </p>
          </Section>

          <Section title="17. Your Rights">
            <p>
              Depending on your location, you may have rights including: the right to access your personal data; the right to correct inaccurate data; the right to request deletion; the right to data portability; and the right to withdraw consent.
            </p>
            <p>
              Canadian residents have rights under the Personal Information Protection and Electronic Documents Act (PIPEDA). Residents of the European Economic Area have rights under the General Data Protection Regulation (GDPR). To exercise any of these rights, contact us using the information below.
            </p>
          </Section>

          <Section title="18. International Users">
            <p>
              WhatYouAte is operated from Canada. If you access the App from outside Canada, your information may be transferred to and processed in Canada. By using the App, you consent to this transfer. We take steps to ensure that data transferred internationally receives an adequate level of protection.
            </p>
          </Section>

          <Section title="19. Cookies and Local Storage">
            <p>
              The App uses browser local storage to save preferences and cached data on your device. This data does not leave your device except as described in this policy. We do not use third-party tracking cookies or advertising trackers.
            </p>
          </Section>

          <Section title="20. Changes to This Policy">
            <p>
              We may update this policy as the App evolves. Material changes will be communicated within the App. The effective date at the top of this page reflects the most recent revision. Continued use of the App after changes are posted constitutes acceptance of the revised policy.
            </p>
          </Section>

          <Section title="21. Contact">
            <p>
              For privacy inquiries, data requests, or any questions about these terms, contact us at:{" "}
              <a href="mailto:hello@whatyouate.app" className="text-primary underline-offset-2 hover:underline">
                hello@whatyouate.app
              </a>
            </p>
          </Section>

        </div>
      </div>
    </div>
  );
}
